version: "3"

x-config:
  etcd_image: &etcd_image bitnami/etcd:3.5.4
  etcd_volumes: &etcd_volumes
    - ./ssl:/opt/etcd/ssl
  etcd_env_basic: &etcd_env_basic
    ALLOW_NONE_AUTHENTICATION: "true"
  etcd_env_mtls: &etcd_env_mtls
    ETCD_CLIENT_CERT_AUTH: "true"
    ETCD_CERT_FILE: /opt/etcd/ssl/server.pem
    ETCD_KEY_FILE: /opt/etcd/ssl/server.key
    ETCD_TRUSTED_CA_FILE: /opt/etcd/ssl/ca.pem

services:
  etcd_mtls:
    image: *etcd_image
    environment:
      <<: *etcd_env_basic
      <<: *etcd_env_mtls
      ETCD_ADVERTISE_CLIENT_URLS: https://0.0.0.0:2379
      ETCD_LISTEN_CLIENT_URLS: https://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes: *etcd_volumes
